Implemented Locator
Dhii/module-locator-abstract pull request #1
Opened 2017-06-08 22:08 UTC by XedinUnknown

Abstract and File-based.

2017-06-16 08:36 UTC, mecha commented on src/ConfigSourceAwareTrait.php
> +    /**
Missing `configSource` property.

2017-07-18 07:41 UTC, mecha requested changes

2017-07-18 07:41 UTC, mecha commented on src/AbstractModuleLocator.php
> +            $configs[md5($_source)] = $this->_read($_source);
The hashing done here should be in a separate method. I assume that this is what `$this->_generateKeyFromSource()` was created for. Perhaps you forgot to change this line?

2017-07-19 07:52 UTC, XedinUnknown commented on src/ConfigSourceAwareTrait.php
> +    /**
Was trying to avoid constraints to the property signature. But you are right, the stricter - the better.

2017-07-19 09:33 UTC, mecha approved these changes
LGTM.

2017-07-19 09:34 UTC, merged